language: python
sudo: required
services:
- docker
env:
  matrix:
  - VARIANT=cpu MESOS=mesos1.7 PYTHON=python3.6 JDK=openjdk8
  - VARIANT=gpu MESOS=mesos1.7 PYTHON=python3.6 JDK=openjdk8
  global:
  - secure: g5fJG0AhPBNxfHhSesyUnZzmPbs17z05R7158EzDF5jmBfrSl4A32oUO6qMJeEjfblgonwJ4pePDti5aPeAw8CiZYzanHpwISASayxf/AzmHLhgdUHAL/GtpcKNKV8LuI7rn+l4bRyEfuCNqZlGK89fPFwLx0xkOGJYwyWzEvalQwsRYk7TbL1XtJpMaNjLV5MIcLcdtKUaQdNCjFbYISVGiDrZaob7aJt/GPtW81QTxAhsAkj4u54Yun9Gj0zUrFf41vAX+LCo+BResq2oRStEvMD9CUIvoLCwlSOhnsp2cQLBM9X/sJim+eVMxEHgXL4yvOf7/ene9PO2LDMkB8ioikW8b/0tILjbinRhnXI+VgHy5DSuvtq6FZU/ypzo9t7/fe3DagPum+eG3sStBLZ6nANccTgOrv4hCUAhq0tvIHVfk56lsScDtX0slR4aPsqksdc/rP/dxPV9I8GFK/G+iaixzfvux5uyQX4Xe5JZsridilitZ0mYRU2mhxsq2ugTlYYeHF/K9DcM6nePg+xgsSGgIkc9I1nk+5kWANVhROslehxN/sPa4/teZ5tvcsK+/QswvxIjCDszW2SSi0LYNmsmZlzLrtmBvtd8W5vNzcINeC+sSWwBi6oRJfNUTj1Js+cxcLxH0gRaNZe9s+CWgj4v5e227i7XEfvZXYvw=
  - secure: Sak0ecGfdi1bIT84o0z8xIoFxwkflefq17dY4PaUAAc+Z1KI4Uw2jEuKCXyujSnyDDLzsrq1BkIw0HBGlEsghQ2exnyCvivWC6YGtknBdXJWlPshjC1QZxDO+6GlXagFsDOKIOKN3sg7fw7NQYeLzEl2rpGQqISzgkz4lY7fA9kKJMtpp/jCWHl2MrWBlrwRvOz82zQXBKH+jhEDUHlzxMSMxvbDgPVGtG2CXIRJIgszJlW32AeKpK0qE5wn+rtaiarM8M+HnOYi+BVi5Hf/vr1KZnsIR4Ep+8bScEf4nPaeUidWdLiV7d7BskGSYUQ6Ea5kJ2gmbsYNXI5f5zRlQMNs6EL8FL2OMpczeIa5ddnqBIn7ki0qqTPO0AsQ9EVuOmNDkOnNK40Fx5nPdTi+CyFMsMHT5PXKEIoEMUFBIoWVGtMkO9KMkW9TJCR8xeWAUcmMOmAhnT0396AuqegvVUcp/EXq3L48rkcq6FIFsGnkjcA9p2VSse9je1UNdmhJEAumBXh2ORnlyKtcldr0XHkMJiw9cG1FQkKQxK6ZXmcuFx371Dufqyzs0bhrrrX1czBLE5gZCDqbaU/gpPFZXZAzWpLC2SEtZxeviu/xwx0ivSM3m1WKXud/QqdPwQJAwZi2nTs/z6oVVQjw4jFoltZg89ymG6QNldmOKtEIgB8=
install:
- export REPO="haowenxu/base-runtime"
- export TAG="${VARIANT}"
- export TAG2="${VARIANT}-${MESOS}-${PYTHON}-${JDK}"
- pip install -r requirements.txt
- python configure.py -c "config/${VARIANT}.yml" -c "config/${MESOS}.yml" -c "config/${PYTHON}.yml" -c "config/${JDK}.yml"
- docker build -t "${REPO}:${TAG}" .
- docker tag "${REPO}:${TAG}" "${REPO}:${TAG2}"
script:
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
- docker push "${REPO}:${TAG}"
- docker push "${REPO}:${TAG2}"
